<?php
/* @var $phpword PHPWord */
$phpword = $this->phpword;

$filename = "tabledemo.docx";
$savePath = PUBLIC_PATH . '/generated/' . $filename;
$linkToFile = '/generated/' . $filename;

$section = $phpword->createSection();

/*
 * Some predefined styles
 */
$cellStyle = array (
        "borderTopSize" => 1,
        "borderRightSize" => 1,
        "borderBottomSize" => 1,
        "borderLeftSize" => 1,
        "borderColor" => '000'
);

/*
 * This is where the demo starts
 */

/* @var $section PHPWord_Section */
$section->addTitle('Table Demo');

$table = $section->addTable();

// Full Width Cell, gridspan 2
$table->addRow();
$table->addCell(9028, $cellStyle, 2)->addText('Test');

// Two Cells
$table->addRow();
$table->addCell(4514, $cellStyle)->addText('Test');
$table->addCell(4514, $cellStyle)->addText('Test');

// Empty Row
$table->addRow();


// Write the file
$objWriter = PHPWord_IOFactory::createWriter($phpword, 'Word2007');

try
{
    $objWriter->save($savePath);
}
catch ( Exception $e )
{
    echo '<pre>';
    var_dump($e);
    die();
}
echo $this->baseUrl($linkToFile);